version: "3.7"

services:
  web:
    environment:
      ST_TOKEN: ${ST_TOKEN:-}
      ST_SYMBOL: ${ST_SYMBOL:-}
      EDITOR: "/usr/bin/vim"
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data   

volumes:
  pg_data:
